as yet unclassified
style
	^ '.news{
	width: 90%;
	margin: 20px 5%;	
}

.newsTitle{
    height: 176px;
    background: url(''http://24.media.tumblr.com/tumblr_m9ndv84PGH1qc2eojo1_1280.png'') center / cover;
    color: #fff;	
    text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
}

.newsDate h3{
	text-align: right;
   margin-right: 24px;
   line-height: 2em;
   font-weight: 700;
   font-size: 14px;
}

.newsDate{
	float: right;}'